name: Java CI with Maven and SonarCloud

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build with Maven
        run: mvn clean verify

      - name: Analyze on SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.projectKey=AlhusseinGhader3_local-restaurant-order-manager -Dsonar.organization=alhusseinghader3 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
